//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.com.pierry.friendly;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageButton;
import android.widget.ImageView;
import br.com.pierry.friendly.R.id;
import br.com.pierry.friendly.R.layout;
import com.google.android.maps.GeoPoint;
import com.google.android.maps.MapView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class LocalizacaoActivity_
    extends LocalizacaoActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.localizacao);
    }

    private void init_(Bundle savedInstanceState) {
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
    }

    private void afterSetContentView_() {
        ibMapa = ((ImageView) findViewById(id.ibMapa));
        ibSatelite = ((ImageView) findViewById(id.ibSatelite));
        ibItem02 = ((ImageButton) findViewById(id.ibItem02));
        ibItem04 = ((ImageButton) findViewById(id.ibItem04));
        ibItem03 = ((ImageButton) findViewById(id.ibItem03));
        ivDescricao = ((ImageView) findViewById(id.ivDescricao));
        ibItem01 = ((ImageButton) findViewById(id.ibItem01));
        ibCenter = ((ImageView) findViewById(id.ibCenter));
        mapa = ((MapView) findViewById(id.mapa));
        {
            View view = findViewById(id.ibCenter);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibCenter();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibSatelite);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibSatelite();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibItem02);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibItem02();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibItem01);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibItem01();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibItem04);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibItem04();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibMapa);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibMapa();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ibItem03);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LocalizacaoActivity_.this.ibItem03();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static LocalizacaoActivity_.IntentBuilder_ intent(Context context) {
        return new LocalizacaoActivity_.IntentBuilder_(context);
    }

    @Override
    public void CriarMe(final String nome, final String cidade, final double lat, final double lg) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocalizacaoActivity_.super.CriarMe(nome, cidade, lat, lg);
                } catch (RuntimeException e) {
                    Log.e("LocalizacaoActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getMapControler(final GeoPoint geo) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocalizacaoActivity_.super.getMapControler(geo);
                } catch (RuntimeException e) {
                    Log.e("LocalizacaoActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void AlterarImagem(final int i) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocalizacaoActivity_.super.AlterarImagem(i);
                } catch (RuntimeException e) {
                    Log.e("LocalizacaoActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void CriarInst(final String nome, final String cidade, final double lat, final double lg) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocalizacaoActivity_.super.CriarInst(nome, cidade, lat, lg);
                } catch (RuntimeException e) {
                    Log.e("LocalizacaoActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void setMapStyle(final int n) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocalizacaoActivity_.super.setMapStyle(n);
                } catch (RuntimeException e) {
                    Log.e("LocalizacaoActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, LocalizacaoActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public LocalizacaoActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
